name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -f backend/pom.xml clean install
    - name: copiar .jar para a Instância EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
        source: "backend/target/showdomilhao-0.0.1-SNAPSHOT.jar"
        target: "/home/ec2-user"
    - name: SSH para a Instância EC2 e Iniciar Aplicação
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
        script: |
          # Parar a aplicação se já estiver em execução
          pkill -f showdomilhao-0.0.1-SNAPSHOT.jar || true
          # Iniciar a aplicação
          nohup java -jar backend/target/showdomilhao-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
          sleep 10
          cat output.log
